In [1]:
import pandas as pd

rain = pd.read_csv("강수량분석자료_20202022.csv", encoding='cp949', )
temp = pd.read_csv('기온분석자료_20202022.csv', encoding='cp949')
humidity = pd.read_csv('습도분석자료_20202022.csv', encoding='cp949')
wind = pd.read_csv('풍속분석자료_20202022.csv', encoding='cp949')

In [2]:
rain.head()

,\t지점번호,지점명,일시,강수량(mm),일최다강수량(mm),일최다강수량일자,1시간최다강수량(mm),1시간최다강수량일자
0,\t108,서울,Jan-20,60.5,46.3,2020-01-07,NaN,NaN
1,\t108,서울,Feb-20,53.1,16.6,2020-02-25,NaN,NaN
2,\t108,서울,Mar-20,16.3,11.8,2020-03-10,NaN,NaN
3,\t108,서울,Apr-20,16.9,10.3,2020-04-19,3.9,2020-04-17
4,\t108,서울,May-20,112.4,29.8,2020-05-18,19.8,2020-05-18

In [3]:
temp.head()

,\t\t지점번호,지점명,일시,평균기온(℃),평균최고기온(℃),최고기온(℃),\t최고기온일자,평균최저기온(℃),최저기온(℃),최저기온일자
0,\t\t108,서울,Jan-20,1.6,5.9,11.9,2020-01-26,-1.7,-6.5,2020-01-01
1,\t\t108,서울,Feb-20,2.5,7.2,15.6,2020-02-15,-1.3,-11.8,2020-02-06
2,\t\t108,서울,Mar-20,7.7,13.3,20.6,2020-03-26,2.6,-2.8,2020-03-05
3,\t\t108,서울,Apr-20,11.1,16.6,23.8,2020-04-16,6.3,1.9,2020-04-05
4,\t\t108,서울,May-20,18.0,23.3,30.0,2020-05-30,13.7,9.2,2020-05-20

In [4]:
humidity.head()

  \t\t지점번호 지점명      일시  평균습도(%rh)  최저습도(%rh)
0  \t\t108  서울  Jan-20       56.0       17.0
1  \t\t108  서울  Feb-20       58.0       14.0
2  \t\t108  서울  Mar-20       46.0       11.0
3  \t\t108  서울  Apr-20       50.0       10.0
4  \t\t108  서울  May-20       67.0       11.0

In [5]:
wind.head()

,\t\t지점번호,지점명,일시,평균풍속(m/s),최대풍속(m/s),최대풍속풍향(deg),\t최대풍속일자,최대순간풍속(m/s),최대순간풍속풍향(deg),\t최대순간풍속일자,\t
0,\t\t108,서울,Jan-20,2.1,7.0,70.0,2020-01-27,13.7,90.0,2020-01-27,NaN
1,\t\t108,서울,Feb-20,2.3,8.2,320.0,2020-02-22,14.4,290.0,2020-02-22,NaN
2,\t\t108,서울,Mar-20,2.5,8.2,250.0,2020-03-19,16.3,270.0,2020-03-19,NaN
3,\t\t108,서울,Apr-20,3.0,8.9,290.0,2020-04-21,17.0,230.0,2020-04-21,NaN
4,\t\t108,서울,May-20,2.4,7.2,70.0,2020-05-19,16.4,290.0,2020-05-18,NaN

In [7]:
# 데이터에서 필요한 칼럼만 가져오기
new_columns = ['일시', '강수량(mm)', '일최다강수량(mm)']
rain = rain[new_columns]

t_new_columns = ['평균기온(℃)',	'평균최고기온(℃)', '최고기온(℃)', '평균최저기온(℃)', '최저기온(℃)']
temp = temp[t_new_columns]
w_new_columns = ['평균풍속(m/s)', '최대풍속(m/s)', '최대순간풍속(m/s)']
wind = wind[w_new_columns]
h_new_columns = ['평균습도(%rh)', '최저습도(%rh)']
humidity = humidity[h_new_columns]

# 행 기준으로 데이터프레임 합치기
df = pd.concat([rain, temp, wind, humidity], axis=1)
df

,일시,강수량(mm),일최다강수량(mm),평균기온(℃),평균최고기온(℃),최고기온(℃),평균최저기온(℃),최저기온(℃),평균풍속(m/s),최대풍속(m/s),최대순간풍속(m/s),평균습도(%rh),최저습도(%rh)
0,Jan-20,60.5,46.3,1.6,5.9,11.9,-1.7,-6.5,2.1,7.0,13.7,56.0,17.0
1,Feb-20,53.1,16.6,2.5,7.2,15.6,-1.3,-11.8,2.3,8.2,14.4,58.0,14.0
2,Mar-20,16.3,11.8,7.7,13.3,20.6,2.6,-2.8,2.5,8.2,16.3,46.0,11.0
3,Apr-20,16.9,10.3,11.1,16.6,23.8,6.3,1.9,3.0,8.9,17.0,50.0,10.0
4,May-20,112.4,29.8,18.0,23.3,30.0,13.7,9.2,2.4,7.2,16.4,67.0,11.0
5,Jun-20,139.6,64.7,23.9,29.0,35.4,19.9,14.8,2.3,7.6,14.5,68.0,26.0
6,Jul-20,270.4,103.1,24.1,28.0,32.9,21.1,17.2,2.4,8.7,16.1,77.0,34.0
7,Aug-20,675.7,102.6,26.5,29.3,34.5,24.4,21.5,2.3,8.3,15.6,85.0,49.0
8,Sep-20,181.5,61.0,21.4,25.6,29.5,18.0,13.6,2.5,9.8,21.5,71.0,27.0
9,Oct-20,0.0,0.0,14.3,19.5,23.6,9.6,3.2,2.1,7.2,13.7,61.0,20.0
10,Nov-20,120.1,86.9,8.0,12.6,20.0,4.0,-3.6,2.2,8.4,15.6,64.0,18.0
11,Dec-20,4.6,2.9,-0.3,3.9,11.4,-4.2,-12.9,2.2,6.5,11.7,58.0,24.0
12,Jan-21,18.9,9.2,-2.4,2.2,13.9,-6.8,-18.6,2.5,8.7,17.5,58.0,19.0
13,Feb-21,7.1,3.4,2.7,7.9,17.4,-2.2,-10.6,2.6,7.5,15.8,56.0,18.0
14,Mar-21,110.9,67.5,9.0,14.8,22.9,4.3,-1.2,2.4,6.9,14.8,63.0,19.0
15,Apr-21,124.1,56.2,14.2,19.5,28.2,9.5,3.1,2.6,7.1,12.5,54.0,18.0
16,May-21,183.1,66.9,17.1,21.9,30.8,12.8,7.3,2.4,8.4,16.0,68.0,25.0
17,Jun-21,104.6,38.2,22.8,27.6,31.6,18.9,13.3,2.2,7.8,15.0,73.0,36.0
18,Jul-21,168.3,67.4,28.1,32.2,36.5,24.6,19.6,2.0,7.4,16.5,71.0,37.0
19,Aug-21,211.2,77.4,25.9,29.7,33.7,22.8,18.1,2.1,8.3,16.4,74.0,39.0
20,Sep-21,131.0,68.1,22.6,26.9,30.3,18.8,16.0,2.3,7.1,12.5,71.0,38.0
21,Oct-21,57.0,14.2,15.6,20.5,28.8,11.6,1.3,2.1,10.6,20.9,70.0,25.0
22,Nov-21,62.4,27.2,8.2,13.1,21.3,4.0,-3.7,2.1,9.3,16.6,68.0,27.0
23,Dec-21,7.9,2.8,0.6,5.1,13.3,-3.5,-15.5,2.3,8.1,15.2,62.0,26.0
24,Jan-22,5.5,1.7,-2.2,2.6,8.4,-6.2,-11.3,2.2,7.6,13.9,55.0,21.0
25,Feb-22,4.7,1.7,-1.1,3.8,11.5,-5.3,-10.7,2.6,7.4,14.5,55.0,21.0
26,Mar-22,102.6,42.1,7.7,12.7,19.5,3.2,-3.0,2.5,8.8,18.5,62.0,15.0
27,Apr-22,20.4,15.5,14.8,20.6,28.7,10.0,3.5,2.7,8.4,14.5,55.0,17.0
28,May-22,7.5,3.5,19.1,25.0,30.7,13.9,7.9,2.6,7.6,14.1,55.0,16.0
29,Jun-22,393.8,176.2,23.3,27.5,32.7,19.8,14.9,2.5,9.9,20.9,73.0,18.0
30,Jul-22,252.3,114.5,27.3,31.0,36.1,24.2,20.8,2.1,5.6,11.6,77.0,46.0
31,Aug-22,564.8,129.6,25.7,28.9,32.9,23.1,16.1,2.3,8.6,24.9,80.0,39.0
32,Sep-22,201.5,120.0,22.4,27.2,32.5,18.2,12.3,2.4,8.0,18.3,68.0,29.0
33,Oct-22,124.1,76.0,14.6,19.7,27.6,10.3,4.4,2.2,6.8,13.7,69.0,25.0
34,Nov-22,84.5,57.9,10.0,15.4,22.1,5.6,-8.1,2.1,6.5,12.0,65.0,23.0
35,Dec-22,13.6,5.4,-2.8,1.7,10.2,-6.6,-13.7,2.3,7.4,15.0,59.0,21.0
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# NaN 값 삭제
df = df.dropna()

# 데이터 저장
df.to_csv('날씨데이터총합.csv', encoding='cp949', index=False)

In [9]:
data = pd.read_csv('날씨데이터총합.csv', encoding='cp949', index_col=0)
data

,강수량(mm),일최다강수량(mm),평균기온(℃),평균최고기온(℃),최고기온(℃),평균최저기온(℃),최저기온(℃),평균풍속(m/s),최대풍속(m/s),최대순간풍속(m/s),평균습도(%rh),최저습도(%rh)
일시,,,,,,,,,,,,
Jan-20,60.5,46.3,1.6,5.9,11.9,-1.7,-6.5,2.1,7.0,13.7,56.0,17.0
Feb-20,53.1,16.6,2.5,7.2,15.6,-1.3,-11.8,2.3,8.2,14.4,58.0,14.0
Mar-20,16.3,11.8,7.7,13.3,20.6,2.6,-2.8,2.5,8.2,16.3,46.0,11.0
Apr-20,16.9,10.3,11.1,16.6,23.8,6.3,1.9,3.0,8.9,17.0,50.0,10.0
May-20,112.4,29.8,18.0,23.3,30.0,13.7,9.2,2.4,7.2,16.4,67.0,11.0
Jun-20,139.6,64.7,23.9,29.0,35.4,19.9,14.8,2.3,7.6,14.5,68.0,26.0
Jul-20,270.4,103.1,24.1,28.0,32.9,21.1,17.2,2.4,8.7,16.1,77.0,34.0
Aug-20,675.7,102.6,26.5,29.3,34.5,24.4,21.5,2.3,8.3,15.6,85.0,49.0
Sep-20,181.5,61.0,21.4,25.6,29.5,18.0,13.6,2.5,9.8,21.5,71.0,27.0
Oct-20,0.0,0.0,14.3,19.5,23.6,9.6,3.2,2.1,7.2,13.7,61.0,20.0
Nov-20,120.1,86.9,8.0,12.6,20.0,4.0,-3.6,2.2,8.4,15.6,64.0,18.0
Dec-20,4.6,2.9,-0.3,3.9,11.4,-4.2,-12.9,2.2,6.5,11.7,58.0,24.0
Jan-21,18.9,9.2,-2.4,2.2,13.9,-6.8,-18.6,2.5,8.7,17.5,58.0,19.0
Feb-21,7.1,3.4,2.7,7.9,17.4,-2.2,-10.6,2.6,7.5,15.8,56.0,18.0
Mar-21,110.9,67.5,9.0,14.8,22.9,4.3,-1.2,2.4,6.9,14.8,63.0,19.0
Apr-21,124.1,56.2,14.2,19.5,28.2,9.5,3.1,2.6,7.1,12.5,54.0,18.0
May-21,183.1,66.9,17.1,21.9,30.8,12.8,7.3,2.4,8.4,16.0,68.0,25.0
Jun-21,104.6,38.2,22.8,27.6,31.6,18.9,13.3,2.2,7.8,15.0,73.0,36.0
Jul-21,168.3,67.4,28.1,32.2,36.5,24.6,19.6,2.0,7.4,16.5,71.0,37.0
Aug-21,211.2,77.4,25.9,29.7,33.7,22.8,18.1,2.1,8.3,16.4,74.0,39.0
Sep-21,131.0,68.1,22.6,26.9,30.3,18.8,16.0,2.3,7.1,12.5,71.0,38.0
Oct-21,57.0,14.2,15.6,20.5,28.8,11.6,1.3,2.1,10.6,20.9,70.0,25.0
Nov-21,62.4,27.2,8.2,13.1,21.3,4.0,-3.7,2.1,9.3,16.6,68.0,27.0
Dec-21,7.9,2.8,0.6,5.1,13.3,-3.5,-15.5,2.3,8.1,15.2,62.0,26.0
Jan-22,5.5,1.7,-2.2,2.6,8.4,-6.2,-11.3,2.2,7.6,13.9,55.0,21.0
Feb-22,4.7,1.7,-1.1,3.8,11.5,-5.3,-10.7,2.6,7.4,14.5,55.0,21.0
Mar-22,102.6,42.1,7.7,12.7,19.5,3.2,-3.0,2.5,8.8,18.5,62.0,15.0
Apr-22,20.4,15.5,14.8,20.6,28.7,10.0,3.5,2.7,8.4,14.5,55.0,17.0
May-22,7.5,3.5,19.1,25.0,30.7,13.9,7.9,2.6,7.6,14.1,55.0,16.0
Jun-22,393.8,176.2,23.3,27.5,32.7,19.8,14.9,2.5,9.9,20.9,73.0,18.0
Jul-22,252.3,114.5,27.3,31.0,36.1,24.2,20.8,2.1,5.6,11.6,77.0,46.0
Aug-22,564.8,129.6,25.7,28.9,32.9,23.1,16.1,2.3,8.6,24.9,80.0,39.0
Sep-22,201.5,120.0,22.4,27.2,32.5,18.2,12.3,2.4,8.0,18.3,68.0,29.0
Oct-22,124.1,76.0,14.6,19.7,27.6,10.3,4.4,2.2,6.8,13.7,69.0,25.0
Nov-22,84.5,57.9,10.0,15.4,22.1,5.6,-8.1,2.1,6.5,12.0,65.0,23.0
Dec-22,13.6,5.4,-2.8,1.7,10.2,-6.6,-13.7,2.3,7.4,15.0,59.0,21.0

In [10]:
# 인덱스 rename
data = data.rename(index={'Jan-20':202001, 'Feb-20':202002, 'Mar-20':202003, 'Apr-20':202004, 'May-20':202005, 'Jun-20':202006, 'Jul-20':202007, 'Aug-20':202008, 'Sep-20':202009, 'Oct-20':202010, 'Nov-20':202011, 'Dec-20':202012, 
                          'Jan-21':202101, 'Feb-21':202102, 'Mar-21':202103, 'Apr-21':202104, 'May-21':202105, 'Jun-21':202106, 'Jul-21':202107, 'Aug-21':202108, 'Sep-21':202109, 'Oct-21':202110, 'Nov-21':202111, 'Dec-21':202112, 
                          'Jan-22':202201, 'Feb-22':202202, 'Mar-22':202203, 'Apr-22':202204, 'May-22':202205, 'Jun-22':202206, 'Jul-22':202207, 'Aug-22':202208, 'Sep-22':202209, 'Oct-22':202210, 'Nov-22':202211, 'Dec-22':202212})
data.head()

,강수량(mm),일최다강수량(mm),평균기온(℃),평균최고기온(℃),최고기온(℃),평균최저기온(℃),최저기온(℃),평균풍속(m/s),최대풍속(m/s),최대순간풍속(m/s),평균습도(%rh),최저습도(%rh)
일시,,,,,,,,,,,,
202001,60.5,46.3,1.6,5.9,11.9,-1.7,-6.5,2.1,7.0,13.7,56.0,17.0
202002,53.1,16.6,2.5,7.2,15.6,-1.3,-11.8,2.3,8.2,14.4,58.0,14.0
202003,16.3,11.8,7.7,13.3,20.6,2.6,-2.8,2.5,8.2,16.3,46.0,11.0
202004,16.9,10.3,11.1,16.6,23.8,6.3,1.9,3.0,8.9,17.0,50.0,10.0
202005,112.4,29.8,18.0,23.3,30.0,13.7,9.2,2.4,7.2,16.4,67.0,11.0

In [11]:
data.to_csv('s_weather.csv', encoding='cp949')