In [119]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [69]:
# crime = pd.read_csv("년,월별 총 범죄데이터.csv", encoding='cp949')
weather = pd.read_csv('s_weather.csv', encoding='cp949')

### 범죄 데이터 필요에 맞게 전처리

In [70]:
# crime.head()

,자치구,20년1월_범죄건수,21년1월_범죄건수,22년1월_범죄건수,20년2월_범죄건수,21년2월_범죄건수,22년2월_범죄건수,20년3월_범죄건수,21년3월_범죄건수,22년3월_범죄건수,...,22년9월_범죄건수,20년10월_범죄건수,21년10월_범죄건수,22년10월_범죄건수,20년11월_범죄건수,21년11월_범죄건수,22년11월_범죄건수,20년12월_범죄건수,21년12월_범죄건수,22년12월_범죄건수
0,강남구,715,438,569,508,338,398,679,487,518,...,549,519,548,580,592,634,706,606,518,630
1,강동구,332,242,324,287,196,222,283,265,244,...,298,310,241,270,312,375,450,292,344,303
2,강북구,258,141,217,242,128,152,258,167,204,...,244,212,201,240,182,227,241,183,191,214
3,강서구,443,258,353,373,223,262,421,286,357,...,368,377,359,471,297,387,434,289,402,343
4,관악구,466,304,378,365,287,284,396,331,310,...,329,469,296,395,431,470,600,461,450,461

In [72]:
# crime_t = crime.T

In [73]:
# crime_t['월_범죄건수'] = crime_t.iloc[:, 1:].sum(axis=1)
# crime_t.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,월_범죄건수
자치구,강남구,강동구,강북구,강서구,관악구,광진구,구로구,금천구,노원구,도봉구,...,성북구,송파구,양천구,영등포구,용산구,은평구,종로구,중구,중랑구,강동구강북구강서구관악구광진구구로구금천구노원구도봉구동대문구동작구마포구서대문구서초구성동...
20년1월_범죄건수,715,332,258,443,466,344,394,222,274,188,...,216,515,255,489,277,329,296,416,280,7702
21년1월_범죄건수,438,242,141,258,304,205,207,184,214,117,...,162,325,211,288,153,230,167,180,230,4982
22년1월_범죄건수,569,324,217,353,378,365,330,249,265,319,...,192,444,304,414,235,319,243,250,212,7092
20년2월_범죄건수,508,287,242,373,365,251,262,264,274,166,...,186,337,265,395,209,242,228,267,275,6074

In [74]:
# crime_t = crime_t.drop(crime_t.index[0])
# crime_t.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,월_범죄건수
20년1월_범죄건수,715,332,258,443,466,344,394,222,274,188,...,216,515,255,489,277,329,296,416,280,7702
21년1월_범죄건수,438,242,141,258,304,205,207,184,214,117,...,162,325,211,288,153,230,167,180,230,4982
22년1월_범죄건수,569,324,217,353,378,365,330,249,265,319,...,192,444,304,414,235,319,243,250,212,7092
20년2월_범죄건수,508,287,242,373,365,251,262,264,274,166,...,186,337,265,395,209,242,228,267,275,6074
21년2월_범죄건수,338,196,128,223,287,215,195,184,207,113,...,145,276,166,184,107,160,184,193,163,4327

In [75]:
# crime_t = crime_t.rename(index=lambda x: '20' + x.replace('년', '').replace('월_범죄건수', '').zfill(2))

# # 변경된 열 이름을 확인
# crime_t.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,월_범죄건수
20201,715,332,258,443,466,344,394,222,274,188,...,216,515,255,489,277,329,296,416,280,7702
20211,438,242,141,258,304,205,207,184,214,117,...,162,325,211,288,153,230,167,180,230,4982
20221,569,324,217,353,378,365,330,249,265,319,...,192,444,304,414,235,319,243,250,212,7092
20202,508,287,242,373,365,251,262,264,274,166,...,186,337,265,395,209,242,228,267,275,6074
20212,338,196,128,223,287,215,195,184,207,113,...,145,276,166,184,107,160,184,193,163,4327

In [76]:
# crime_t = crime_t.rename(index={'20201':202001, '20202':202002, '20203':202003, '20204':202004, '20205':202005, '20206':202006, '20207':202007, '20208':202008, '20209':202009, 
#                           '20211':202101, '20212':202102, '20213':202103, '20214':202104, '20215':202105, '20216':202106, '20217':202107, '20218':202108, '20219':202109,
#                           '20221':202201, '20222':202202, '20223':202203, '20224':202204, '20225':202205, '20226':202206, '20227':202207, '20228':202208, '20229':202209})
# crime_t

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,월_범죄건수
202001,715,332,258,443,466,344,394,222,274,188,...,216,515,255,489,277,329,296,416,280,7702
202101,438,242,141,258,304,205,207,184,214,117,...,162,325,211,288,153,230,167,180,230,4982
202201,569,324,217,353,378,365,330,249,265,319,...,192,444,304,414,235,319,243,250,212,7092
202002,508,287,242,373,365,251,262,264,274,166,...,186,337,265,395,209,242,228,267,275,6074
202102,338,196,128,223,287,215,195,184,207,113,...,145,276,166,184,107,160,184,193,163,4327
202202,398,222,152,262,284,180,221,144,175,212,...,109,271,175,282,169,214,187,181,181,4732
202003,679,283,258,421,396,297,322,239,266,169,...,220,473,239,440,282,277,310,326,333,6843
202103,487,265,167,286,331,272,295,170,250,154,...,185,392,252,360,168,253,218,227,272,5896
202203,518,244,204,357,310,241,261,169,197,271,...,147,398,226,360,183,265,199,268,177,5810
202004,604,264,252,330,456,276,310,193,306,176,...,217,475,238,412,291,259,211,230,292,6462
202104,487,269,197,337,367,250,306,207,257,147,...,177,394,240,386,201,243,193,229,215,5942
202204,534,273,231,379,392,308,284,165,211,275,...,191,411,281,377,177,277,211,324,218,6418
202005,582,299,243,371,459,290,386,233,370,170,...,185,515,244,493,266,259,253,258,301,6948
202105,514,271,210,327,399,255,301,218,292,159,...,185,366,259,331,176,232,228,261,241,6091
202205,617,313,302,382,355,309,348,202,265,370,...,187,425,263,432,246,280,249,297,287,7168
202006,631,330,253,371,441,298,367,224,308,202,...,200,474,260,439,237,317,280,286,316,6883
202106,560,325,207,325,412,253,289,185,304,172,...,186,471,252,343,230,334,213,259,318,6595
202206,579,325,295,416,423,338,391,252,283,358,...,213,489,296,435,298,328,266,323,300,7783
202007,641,373,265,369,494,328,472,247,331,192,...,265,493,335,513,249,337,281,325,397,7675
202107,549,321,224,343,433,280,264,230,331,170,...,220,413,229,408,261,279,266,266,310,6817
202207,624,360,230,465,463,298,347,284,284,356,...,219,416,259,433,312,287,226,347,261,7526
202008,651,357,222,380,2409,354,343,209,342,182,...,225,440,278,461,221,272,227,293,297,8827
202108,578,284,202,321,373,275,356,207,322,138,...,215,450,231,449,222,319,264,292,274,6806
202208,643,329,262,433,489,286,372,238,288,340,...,221,470,347,412,274,312,150,202,206,7236
202009,296,89,210,139,252,116,295,362,341,184,...,804,346,99,358,291,759,418,316,226,7164
202109,495,325,206,328,322,191,313,213,302,129,...,208,367,283,324,189,306,246,266,295,6183
202209,549,298,244,368,329,297,309,194,268,342,...,142,403,216,324,252,291,211,315,263,6535
202010,519,310,212,377,469,335,358,222,304,176,...,218,341,288,339,239,277,270,261,338,6599
202110,548,241,201,359,296,226,321,208,263,156,...,215,355,227,257,166,290,193,221,293,5978
202210,580,270,240,471,395,292,361,247,232,327,...,180,431,255,335,245,325,237,348,272,7079
202011,592,312,182,297,431,240,300,186,301,176,...,220,466,233,435,229,262,218,235,265,6247
202111,634,375,227,387,470,353,313,198,398,237,...,268,478,357,483,247,312,298,254,348,7822
202211,706,450,241,434,600,382,356,261,309,393,...,209,537,291,599,302,312,275,299,417,8752
202012,606,292,183,289,461,270,300,176,325,209,...,197,448,255,456,210,283,293,251,345,6821
202112,518,344,191,402,450,312,326,235,285,168,...,245,427,308,366,261,286,260,213,251,6878
202212,630,303,214,343,461,323,277,172,294,333,...,184,472,256,416,274,277,208,312,257,7014

In [78]:
# crime_t.index = crime_t.index.astype(int)
# crime_t = crime_t.sort_index()
# crime_t

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,월_범죄건수
202001,715,332,258,443,466,344,394,222,274,188,...,216,515,255,489,277,329,296,416,280,7702
202002,508,287,242,373,365,251,262,264,274,166,...,186,337,265,395,209,242,228,267,275,6074
202003,679,283,258,421,396,297,322,239,266,169,...,220,473,239,440,282,277,310,326,333,6843
202004,604,264,252,330,456,276,310,193,306,176,...,217,475,238,412,291,259,211,230,292,6462
202005,582,299,243,371,459,290,386,233,370,170,...,185,515,244,493,266,259,253,258,301,6948
202006,631,330,253,371,441,298,367,224,308,202,...,200,474,260,439,237,317,280,286,316,6883
202007,641,373,265,369,494,328,472,247,331,192,...,265,493,335,513,249,337,281,325,397,7675
202008,651,357,222,380,2409,354,343,209,342,182,...,225,440,278,461,221,272,227,293,297,8827
202009,296,89,210,139,252,116,295,362,341,184,...,804,346,99,358,291,759,418,316,226,7164
202010,519,310,212,377,469,335,358,222,304,176,...,218,341,288,339,239,277,270,261,338,6599
202011,592,312,182,297,431,240,300,186,301,176,...,220,466,233,435,229,262,218,235,265,6247
202012,606,292,183,289,461,270,300,176,325,209,...,197,448,255,456,210,283,293,251,345,6821
202101,438,242,141,258,304,205,207,184,214,117,...,162,325,211,288,153,230,167,180,230,4982
202102,338,196,128,223,287,215,195,184,207,113,...,145,276,166,184,107,160,184,193,163,4327
202103,487,265,167,286,331,272,295,170,250,154,...,185,392,252,360,168,253,218,227,272,5896
202104,487,269,197,337,367,250,306,207,257,147,...,177,394,240,386,201,243,193,229,215,5942
202105,514,271,210,327,399,255,301,218,292,159,...,185,366,259,331,176,232,228,261,241,6091
202106,560,325,207,325,412,253,289,185,304,172,...,186,471,252,343,230,334,213,259,318,6595
202107,549,321,224,343,433,280,264,230,331,170,...,220,413,229,408,261,279,266,266,310,6817
202108,578,284,202,321,373,275,356,207,322,138,...,215,450,231,449,222,319,264,292,274,6806
202109,495,325,206,328,322,191,313,213,302,129,...,208,367,283,324,189,306,246,266,295,6183
202110,548,241,201,359,296,226,321,208,263,156,...,215,355,227,257,166,290,193,221,293,5978
202111,634,375,227,387,470,353,313,198,398,237,...,268,478,357,483,247,312,298,254,348,7822
202112,518,344,191,402,450,312,326,235,285,168,...,245,427,308,366,261,286,260,213,251,6878
202201,569,324,217,353,378,365,330,249,265,319,...,192,444,304,414,235,319,243,250,212,7092
202202,398,222,152,262,284,180,221,144,175,212,...,109,271,175,282,169,214,187,181,181,4732
202203,518,244,204,357,310,241,261,169,197,271,...,147,398,226,360,183,265,199,268,177,5810
202204,534,273,231,379,392,308,284,165,211,275,...,191,411,281,377,177,277,211,324,218,6418
202205,617,313,302,382,355,309,348,202,265,370,...,187,425,263,432,246,280,249,297,287,7168
202206,579,325,295,416,423,338,391,252,283,358,...,213,489,296,435,298,328,266,323,300,7783
202207,624,360,230,465,463,298,347,284,284,356,...,219,416,259,433,312,287,226,347,261,7526
202208,643,329,262,433,489,286,372,238,288,340,...,221,470,347,412,274,312,150,202,206,7236
202209,549,298,244,368,329,297,309,194,268,342,...,142,403,216,324,252,291,211,315,263,6535
202210,580,270,240,471,395,292,361,247,232,327,...,180,431,255,335,245,325,237,348,272,7079
202211,706,450,241,434,600,382,356,261,309,393,...,209,537,291,599,302,312,275,299,417,8752
202212,630,303,214,343,461,323,277,172,294,333,...,184,472,256,416,274,277,208,312,257,7014

In [80]:
# df = crime_t[['월_범죄건수']]
# df.to_csv('crime_seoul_all.csv', encoding='cp949')

In [84]:
# # 칼럼 변경
# df = pd.read_csv('crime_seoul_all.csv', encoding='cp949')
# df = df.rename(columns={'Unnamed: 0': '일시'})
# df.to_csv('crime_seoul_all.csv', encoding='cp949')
# df.head()

       일시  월_범죄건수
0  202001    7702
1  202002    6074
2  202003    6843
3  202004    6462
4  202005    6948

### 범죄 데이터 전처리 완료

In [86]:
month_crime = pd.read_csv('crime_seoul_all.csv', encoding='cp949', index_col=0)
month_crime.head()

       일시  월_범죄건수
0  202001    7702
1  202002    6074
2  202003    6843
3  202004    6462
4  202005    6948

In [87]:
weather.head()

,일시,강수량(mm),일최다강수량(mm),평균기온(℃),평균최고기온(℃),최고기온(℃),평균최저기온(℃),최저기온(℃),평균풍속(m/s),최대풍속(m/s),최대순간풍속(m/s),평균습도(%rh),최저습도(%rh)
0,202001,60.5,46.3,1.6,5.9,11.9,-1.7,-6.5,2.1,7.0,13.7,56.0,17.0
1,202002,53.1,16.6,2.5,7.2,15.6,-1.3,-11.8,2.3,8.2,14.4,58.0,14.0
2,202003,16.3,11.8,7.7,13.3,20.6,2.6,-2.8,2.5,8.2,16.3,46.0,11.0
3,202004,16.9,10.3,11.1,16.6,23.8,6.3,1.9,3.0,8.9,17.0,50.0,10.0
4,202005,112.4,29.8,18.0,23.3,30.0,13.7,9.2,2.4,7.2,16.4,67.0,11.0

In [88]:
weather.columns

Index(['일시', '강수량(mm)', '일최다강수량(mm)', '평균기온(℃)', '평균최고기온(℃)', '최고기온(℃)',
       '평균최저기온(℃)', '최저기온(℃)', '평균풍속(m/s)', '최대풍속(m/s)', '최대순간풍속(m/s)',
       '평균습도(%rh)', '최저습도(%rh)'],
      dtype='object')

In [90]:
df = pd.merge(month_crime, weather, on='일시')

In [133]:
# RandomForest
# 독립 변수와 종속 변수 설정
X = df[['강수량(mm)', '일최다강수량(mm)', '평균기온(℃)', '평균최고기온(℃)', '최고기온(℃)',
       '평균최저기온(℃)', '최저기온(℃)', '평균풍속(m/s)', '최대풍속(m/s)', '최대순간풍속(m/s)',
       '평균습도(%rh)', '최저습도(%rh)']] # 독립 변수
y = df['월_범죄건수'] # 종속 변수

# 훈련 데이터와 테스트 데이터로 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 랜덤 포레스트 회귀 모델 생성
model = RandomForestRegressor(n_estimators=100, random_state=42)

# 모델 학습
model.fit(X_train, y_train)

# 테스트 데이터로 예측
y_pred = model.predict(X_test)

# 평가 지표 계산 (예: 평균 제곱 오차)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

# MAE 계산
mae = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error:", mae)

# RMSE 계산
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error:", rmse)

Mean Squared Error: 1306629.9481625003
Mean Absolute Error: 993.19375
Root Mean Squared Error: 1143.079152186103

In [89]:
# 다변량 회귀 분석 모델 생성
X = df[['강수량(mm)', '일최다강수량(mm)', '평균기온(℃)', '평균최고기온(℃)', '최고기온(℃)',
       '평균최저기온(℃)', '최저기온(℃)', '평균풍속(m/s)', '최대풍속(m/s)', '최대순간풍속(m/s)',
       '평균습도(%rh)', '최저습도(%rh)']] # 독립 변수
y = df['월_범죄건수'] # 종속 변수

X = sm.add_constant(X) # 상수항 추가

model = sm.OLS(y, X).fit() # 최소자승법(OLS)을 사용하여 모델 학습

# 회귀 분석 결과 출력
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 월_범죄건수   R-squared:                       0.595
Model:                            OLS   Adj. R-squared:                  0.384
Method:                 Least Squares   F-statistic:                     2.819
Date:                Tue, 16 Apr 2024   Prob (F-statistic):             0.0158
Time:                        20:55:04   Log-Likelihood:                -281.08
No. Observations:                  36   AIC:                             588.2
Df Residuals:                      23   BIC:                             608.8
Df Model:                          12
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const        1.211e+04   4210.881      2.876      0.009    3398.324    2.08e+04
강수량(mm)         5.1227      2.281      2.246      0.035       0.404       9.841
일최다강수량(mm)     -0.8383      5.675     -0.148      0.884     -12.578      10.902
평균기온(℃)     -1950.9886   1330.952     -1.466      0.156   -4704.273     802.296
평균최고기온(℃)    1176.7998    702.250      1.676      0.107    -275.915    2629.514
최고기온(℃)      -228.9525    117.388     -1.950      0.063    -471.788      13.883
평균최저기온(℃)    1092.9157    736.526      1.484      0.151    -430.704    2616.535
최저기온(℃)       -91.1740     73.490     -1.241      0.227    -243.201      60.853
평균풍속(m/s)   -1256.0812    980.836     -1.281      0.213   -3285.096     772.934
최대풍속(m/s)     280.6980    221.304      1.268      0.217    -177.104     738.500
최대순간풍속(m/s)  -182.2686     87.220     -2.090      0.048    -362.698      -1.840
평균습도(%rh)     -19.8318     45.398     -0.437      0.666    -113.745      74.082
최저습도(%rh)     -25.7748     35.273     -0.731      0.472     -98.743      47.193
==============================================================================
Omnibus:                        0.935   Durbin-Watson:                   1.480
Prob(Omnibus):                  0.627   Jarque-Bera (JB):                0.829
Skew:                          -0.083   Prob(JB):                        0.661
Kurtosis:                       2.275   Cond. No.                     7.41e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.41e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [99]:
# 다변량 회귀 분석 모델 생성
X = df[['강수량(mm)', '일최다강수량(mm)', '평균기온(℃)', '평균최고기온(℃)', '최고기온(℃)',
       '평균최저기온(℃)', '최저기온(℃)', '평균풍속(m/s)', '최대풍속(m/s)', '최대순간풍속(m/s)',
       '평균습도(%rh)', '최저습도(%rh)']] # 독립 변수
y = df['월_범죄건수'] # 종속 변수

X = sm.add_constant(X) # 상수항 추가

model = sm.OLS(y, X).fit() # 최소자승법(OLS)을 사용하여 모델 학습

# 회귀 분석 결과 출력
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 월_범죄건수   R-squared:                       0.595
Model:                            OLS   Adj. R-squared:                  0.384
Method:                 Least Squares   F-statistic:                     2.819
Date:                Tue, 16 Apr 2024   Prob (F-statistic):             0.0158
Time:                        21:53:10   Log-Likelihood:                -281.08
No. Observations:                  36   AIC:                             588.2
Df Residuals:                      23   BIC:                             608.8
Df Model:                          12
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const        1.211e+04   4210.881      2.876      0.009    3398.324    2.08e+04
강수량(mm)         5.1227      2.281      2.246      0.035       0.404       9.841
일최다강수량(mm)     -0.8383      5.675     -0.148      0.884     -12.578      10.902
평균기온(℃)     -1950.9886   1330.952     -1.466      0.156   -4704.273     802.296
평균최고기온(℃)    1176.7998    702.250      1.676      0.107    -275.915    2629.514
최고기온(℃)      -228.9525    117.388     -1.950      0.063    -471.788      13.883
평균최저기온(℃)    1092.9157    736.526      1.484      0.151    -430.704    2616.535
최저기온(℃)       -91.1740     73.490     -1.241      0.227    -243.201      60.853
평균풍속(m/s)   -1256.0812    980.836     -1.281      0.213   -3285.096     772.934
최대풍속(m/s)     280.6980    221.304      1.268      0.217    -177.104     738.500
최대순간풍속(m/s)  -182.2686     87.220     -2.090      0.048    -362.698      -1.840
평균습도(%rh)     -19.8318     45.398     -0.437      0.666    -113.745      74.082
최저습도(%rh)     -25.7748     35.273     -0.731      0.472     -98.743      47.193
==============================================================================
Omnibus:                        0.935   Durbin-Watson:                   1.480
Prob(Omnibus):                  0.627   Jarque-Bera (JB):                0.829
Skew:                          -0.083   Prob(JB):                        0.661
Kurtosis:                       2.275   Cond. No.                     7.41e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.41e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

## 인구 데이터 - RandomForest

In [132]:
pop = pd.read_csv('crime_pop_all.csv', encoding='cp949')
pop.head()

,자치구,2020_20대_남자,2020_30대_남자,2020_40대_남자,2020_50대_남자,2021_20대_남자,2021_30대_남자,2021_40대_남자,2021_50대_남자,2022_20대_남자,...,2020_고령자,2021_세대수,2021_한국인,2021_등록외국인,2021_고령자,2022_세대수,2022_한국인,2022_등록외국인,2022_고령자,총범죄건수
0,강남구,5736,10181,5750,3512,5733,10501,6018,4008,5765,...,75096,234233,533042,4758,78226,232777,529102,5001,81715,20117
1,강동구,3599,6026,4357,4360,4321,6713,4572,4672,4389,...,70019,201613,462664,3808,74070,202169,460067,3970,78340,10697
2,강북구,3119,3973,3644,4240,3387,4239,3642,4447,3639,...,63422,144536,299182,3381,64333,144313,293660,4042,66307,7913
3,강서구,7431,12363,6444,5323,8264,13593,6877,5584,8684,...,88984,271175,574315,5453,92558,273697,569166,5472,97128,12719
4,관악구,24849,20454,8698,6451,25945,21558,9189,6902,27855,...,78875,276597,485699,13750,79871,283623,486752,14474,82447,16422

In [105]:
pop.columns

Index(['자치구', '2020_20대_남자', '2020_30대_남자', '2020_40대_남자', '2020_50대_남자',
       '2021_20대_남자', '2021_30대_남자', '2021_40대_남자', '2021_50대_남자',
       '2022_20대_남자', '2022_30대_남자', '2022_40대_남자', '2022_50대_남자',
       '2020_20대_여자', '2020_30대_여자', '2020_40대_여자', '2020_50대_여자',
       '2021_20대_여자', '2021_30대_여자', '2021_40대_여자', '2021_50대_여자',
       '2022_20대_여자', '2022_30대_여자', '2022_40대_여자', '2022_50대_여자', '2020_세대수',
       '2020_한국인', '2020_등록외국인', '2020_고령자', '2021_세대수', '2021_한국인',
       '2021_등록외국인', '2021_고령자', '2022_세대수', '2022_한국인', '2022_등록외국인',
       '2022_고령자', '총범죄건수'],
      dtype='object')

In [124]:
pip install lightgbm

Collecting lightgbm
  Obtaining dependency information for lightgbm from https://files.pythonhosted.org/packages/e1/4c/4685ccfae9806f561de716e32549190c1f533dde5bcadaf83bdf23972cf0/lightgbm-4.3.0-py3-none-win_amd64.whl.metadata
  Downloading lightgbm-4.3.0-py3-none-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy in c:\users\sugye\anaconda3\lib\site-packages (from lightgbm) (1.24.3)
Requirement already satisfied: scipy in c:\users\sugye\anaconda3\lib\site-packages (from lightgbm) (1.11.1)
Downloading lightgbm-4.3.0-py3-none-win_amd64.whl (1.3 MB)
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
    --------------------------------------- 0.0/1.3 MB ? eta -:--:--
   -- ------------------------------------- 0.1/1.3 MB 1.1 MB/s eta 0:00:02
   ------ --------------------------------- 0.2/1.3 MB 1.9 MB/s eta 0:00:01
   ------------- -------------------------- 0.5/1.3 MB 2.6 MB/s eta 0:00:01
   ---------------------------- ----------- 0.9/1.3 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------  1.3/1.3 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 1.3/1.3 MB 4.7 MB/s eta 0:00:00
Installing collected packages: lightgbm
Successfully installed lightgbm-4.3.0
Note: you may need to restart the kernel to use updated packages.

In [125]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from lightgbm import LGBMRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error, mean_squared_error

# 독립 변수와 종속 변수 설정
X = pop[['2020_30대_남자', '2021_30대_남자', '2022_30대_남자', '2020_40대_여자', '2021_40대_여자', '2022_40대_여자']]  # 독립 변수들의 열을 지정합니다.
y = pop['총범죄건수']  # 종속 변수를 지정합니다.

In [127]:
# 훈련 데이터와 테스트 데이터로 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# 랜덤 포레스트 회귀 모델 생성
model = RandomForestRegressor(n_estimators=100, random_state=42)

# 모델 학습
model.fit(X_train, y_train)

# 테스트 데이터로 예측
y_pred = model.predict(X_test)

# 평가 지표 계산 (예: 평균 제곱 오차)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

# MAE 계산
mae = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error:", mae)

# RMSE 계산
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error:", rmse)

Mean Squared Error: 6159809.284012502
Mean Absolute Error: 1669.7012500000003
Root Mean Squared Error: 2481.8963080702024

In [128]:
# 훈련 데이터와 테스트 데이터로 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# 선형 회귀 모델 생성
model = LinearRegression()

# 모델 학습
model.fit(X_train, y_train)

# 테스트 데이터로 예측
y_pred = model.predict(X_test)

# 평가 지표 계산 (예: 평균 제곱 오차)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

# MAE 계산
mae = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error:", mae)

# RMSE 계산
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error:", rmse)

Mean Squared Error: 10610124.653927406
Mean Absolute Error: 2320.3627180838307
Root Mean Squared Error: 3257.318629475386

In [129]:
# 훈련 데이터와 테스트 데이터로 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# LightGBM 회귀 모델 생성
model = LGBMRegressor(random_state=42)

# 모델 학습
model.fit(X_train, y_train)

# 테스트 데이터로 예측
y_pred = model.predict(X_test)

# 평가 지표 계산 (예: 평균 제곱 오차)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

# MAE 계산
mae = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error:", mae)

# RMSE 계산
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error:", rmse)

[LightGBM] [Warning] There are no meaningful features which satisfy the provided configuration. Decreasing Dataset parameters min_data_in_bin or min_data_in_leaf and re-constructing Dataset might resolve this warning.
[LightGBM] [Info] Total Bins 0
[LightGBM] [Info] Number of data points in the train set: 17, number of used features: 0
[LightGBM] [Info] Start training from score 10427.705882
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
Mean Squared Error: 13973461.476211073
Mean Absolute Error: 2348.2279411764703
Root Mean Squared Error: 3738.109345138405

### RandomForest 모델 성능 향상

In [130]:
# 이상치 식별 및 처리 함수 정의
def remove_outliers(df, column, threshold=3):
    mean = np.mean(df[column])
    std = np.std(df[column])
    outliers = df[(df[column] - mean) / std > threshold]
    df = df.drop(outliers.index)
    return df

# 이상치 식별 및 처리
threshold = 3  # 임계값 설정
column = '총범죄건수'  # 대상 칼럼 설정
pop_no_outliers = remove_outliers(pop, column, threshold)

# 처리 후 데이터 확인
print("이상치 처리 전 데이터 개수:", len(pop))
print("이상치 처리 후 데이터 개수:", len(pop_no_outliers))

이상치 처리 전 데이터 개수: 25
이상치 처리 후 데이터 개수: 24

In [137]:
# 독립 변수와 종속 변수 설정
X = pop_no_outliers[['2020_30대_남자', '2021_30대_남자', '2022_30대_남자', '2020_40대_여자', '2021_40대_여자', '2022_40대_여자']]  # 독립 변수들의 열을 지정합니다.
y = pop_no_outliers['총범죄건수']  # 종속 변수를 지정합니다.

# 훈련 데이터와 테스트 데이터로 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# 랜덤 포레스트 회귀 모델 생성
model = RandomForestRegressor(n_estimators=100, random_state=42)

# 모델 학습
model.fit(X_train, y_train)

# 테스트 데이터로 예측
y_pred = model.predict(X_test)

# 평가 지표 계산 (예: 평균 제곱 오차)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

# MAE 계산
mae = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error:", mae)

# RMSE 계산
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error:", rmse)

Mean Squared Error: 4863659.3064125
Mean Absolute Error: 1865.80375
Root Mean Squared Error: 2205.3705598861384

In [141]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import VotingRegressor

# 각각의 기본 모델 설정
model1 = RandomForestRegressor(n_estimators=100, random_state=42)
model2 = RandomForestRegressor(n_estimators=200, random_state=42)
model3 = RandomForestRegressor(n_estimators=300, random_state=42)

# VotingRegressor 생성
ensemble_model_rf = VotingRegressor(estimators=[('rf1', model1), ('rf2', model2), ('rf3', model3)])

# 모델 학습
ensemble_model_rf.fit(X_train, y_train)

# 테스트 데이터로 예측
y_pred_rf = ensemble_model_rf.predict(X_test)

# 평가 지표 계산 (예: 평균 제곱 오차)
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
print("Mean Squared Error (Random Forest Ensemble):", rmse_rf)
print("예측 결과 : ", y_pred_rf)

Mean Squared Error (Random Forest Ensemble): 2177.6505928206916
예측 결과 :  [ 9032.06       12117.265       9886.195      10687.94888889
 11721.51444444  8547.40388889 10333.75111111  9091.33333333]