In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
pop_male = pd.read_csv('1인가구_남자.csv', encoding='cp949', index_col=0)
pop_male.head()

,2020_20대_남자,2020_30대_남자,2020_40대_남자,2020_50대_남자,2021_20대_남자,2021_30대_남자,2021_40대_남자,2021_50대_남자,2022_20대_남자,2022_30대_남자,2022_40대_남자,2022_50대_남자
자치구별(2),,,,,,,,,,,,
강남구,5736,10181,5750,3512,5733,10501,6018,4008,5765,10686,6172,4122
강동구,3599,6026,4357,4360,4321,6713,4572,4672,4389,6974,4557,4813
강북구,3119,3973,3644,4240,3387,4239,3642,4447,3639,4485,3679,4569
강서구,7431,12363,6444,5323,8264,13593,6877,5584,8684,14599,7188,5797
관악구,24849,20454,8698,6451,25945,21558,9189,6902,27855,23214,9407,7145

In [5]:
pop_female = pd.read_csv('1인가구_여자.csv', encoding='cp949', index_col=0)
pop_female.head()

,2020_20대_여자,2020_30대_여자,2020_40대_여자,2020_50대_여자,2021_20대_여자,2021_30대_여자,2021_40대_여자,2021_50대_여자,2022_20대_여자,2022_30대_여자,2022_40대_여자,2022_50대_여자
자치구별(2),,,,,,,,,,,,
강남구,9075,11286,5804,3340,9053,11137,6178,3637,9033,11018,6384,3806
강동구,5362,4755,3172,3117,6610,5482,3412,3341,6903,5891,3571,3405
강북구,4812,2738,2420,3238,5090,2944,2389,3260,5545,3146,2389,3405
강서구,12654,9712,4808,4532,14150,11191,5138,4655,15006,12501,5447,4687
관악구,27375,12690,4638,3960,28679,13554,4812,4071,30625,14745,5096,4217

In [4]:
crime = pd.read_csv('년,월별 총 범죄데이터.csv', encoding='cp949', index_col=0)
crime.head()

,20년1월_범죄건수,21년1월_범죄건수,22년1월_범죄건수,20년2월_범죄건수,21년2월_범죄건수,22년2월_범죄건수,20년3월_범죄건수,21년3월_범죄건수,22년3월_범죄건수,20년4월_범죄건수,...,22년9월_범죄건수,20년10월_범죄건수,21년10월_범죄건수,22년10월_범죄건수,20년11월_범죄건수,21년11월_범죄건수,22년11월_범죄건수,20년12월_범죄건수,21년12월_범죄건수,22년12월_범죄건수
자치구,,,,,,,,,,,,,,,,,,,,,
강남구,715,438,569,508,338,398,679,487,518,604,...,549,519,548,580,592,634,706,606,518,630
강동구,332,242,324,287,196,222,283,265,244,264,...,298,310,241,270,312,375,450,292,344,303
강북구,258,141,217,242,128,152,258,167,204,252,...,244,212,201,240,182,227,241,183,191,214
강서구,443,258,353,373,223,262,421,286,357,330,...,368,377,359,471,297,387,434,289,402,343
관악구,466,304,378,365,287,284,396,331,310,456,...,329,469,296,395,431,470,600,461,450,461

In [13]:
crime_rate = pd.read_csv('년도별 범죄율 데이터만.csv', encoding='cp949')
crime_rate

     자치구   20년_범죄율   21년_범죄율   22년_범죄율  총범죄건수
0    강남구  0.349157  0.305513  0.345330  20117
1    강동구  0.329812  0.323268  0.346920  10697
2    강북구  0.351321  0.290787  0.357892   7913
3    강서구  0.327070  0.306313  0.366617  12719
4    관악구  0.432286  0.270613  0.297101  16422
5    광진구  0.336368  0.305492  0.358140  10105
6    구로구  0.358802  0.304401  0.336797  11452
7    금천구  0.356345  0.312973  0.330681   7793
8    노원구  0.365501  0.334538  0.299961  10238
9    도봉구  0.275610  0.234080  0.490310   7946
10  동대문구  0.396378  0.350219  0.253403   8449
11   동작구  0.357221  0.287415  0.355364   9154
12   마포구  0.354424  0.364198  0.281379   9720
13  서대문구  0.279937  0.257343  0.462720   8852
14   서초구  0.184584  0.494388  0.321028   7395
15   성동구  0.281229  0.231022  0.487749   9142
16   성북구  0.406419  0.310776  0.282805   7758
17   송파구  0.350105  0.310050  0.339845  15204
18   양천구  0.325848  0.328682  0.345470   9173
19  영등포구  0.367585  0.293717  0.338698  14228
20   용산구  0.359444  0.285184  0.355372   8349
21   은평구  0.365240  0.305922  0.328838  10604
22   종로구  0.378587  0.314625  0.306788   8677
23    중구  0.353794  0.292207  0.353999   9791
24   중랑구  0.369232  0.323393  0.307375   9926

In [11]:
pip install dataframe_image

Collecting dataframe_image
  Obtaining dependency information for dataframe_image from https://files.pythonhosted.org/packages/ef/40/9e8d11ae1eb3884c6a8c150d7c7aec63079078b59cbf23581e9a156ce462/dataframe_image-0.2.3-py3-none-any.whl.metadata
  Downloading dataframe_image-0.2.3-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: pandas>=0.24 in c:\users\sugye\anaconda3\lib\site-packages (from dataframe_image) (2.0.3)
Requirement already satisfied: nbconvert>=5 in c:\users\sugye\anaconda3\lib\site-packages (from dataframe_image) (6.5.4)
Requirement already satisfied: aiohttp in c:\users\sugye\anaconda3\lib\site-packages (from dataframe_image) (3.8.5)
Requirement already satisfied: requests in c:\users\sugye\anaconda3\lib\site-packages (from dataframe_image) (2.31.0)
Requirement already satisfied: pillow in c:\users\sugye\anaconda3\lib\site-packages (from dataframe_image) (9.4.0)
Requirement already satisfied: packaging in c:\users\sugye\anaconda3\lib\site-packages (from dataframe_image) (23.1)
Requirement already satisfied: mistune in c:\users\sugye\anaconda3\lib\site-packages (from dataframe_image) (0.8.4)
Requirement already satisfied: lxml in c:\users\sugye\anaconda3\lib\site-packages (from dataframe_image) (4.9.3)
Requirement already satisfied: beautifulsoup4 in c:\users\sugye\anaconda3\lib\site-packages (from dataframe_image) (4.12.2)
Collecting cssutils (from dataframe_image)
  Obtaining dependency information for cssutils from https://files.pythonhosted.org/packages/97/67/9a7e56eedd2177f468efe17cfb96eda89aa65daabb472d77f4040e585cb9/cssutils-2.11.0-py3-none-any.whl.metadata
  Downloading cssutils-2.11.0-py3-none-any.whl.metadata (8.8 kB)
Collecting html2image (from dataframe_image)
  Obtaining dependency information for html2image from https://files.pythonhosted.org/packages/89/b9/1dc02a535c71ceed5b71bd0f82e5d31fba100b59d43a35d5c40d836a8525/html2image-2.0.4.3-py3-none-any.whl.metadata
  Downloading html2image-2.0.4.3-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: bleach in c:\users\sugye\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image) (4.1.0)
Requirement already satisfied: defusedxml in c:\users\sugye\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image) (0.7.1)
Requirement already satisfied: entrypoints>=0.2.2 in c:\users\sugye\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image) (0.4)
Requirement already satisfied: jinja2>=3.0 in c:\users\sugye\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image) (3.1.2)
Requirement already satisfied: jupyter-core>=4.7 in c:\users\sugye\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image) (5.3.0)
Requirement already satisfied: jupyterlab-pygments in c:\users\sugye\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\sugye\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image) (2.1.1)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\sugye\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image) (0.5.13)
Requirement already satisfied: nbformat>=5.1 in c:\users\sugye\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image) (5.9.2)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\sugye\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image) (1.5.0)
Requirement already satisfied: pygments>=2.4.1 in c:\users\sugye\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image) (2.15.1)
Requirement already satisfied: tinycss2 in c:\users\sugye\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image) (1.2.1)
Requirement already satisfied: traitlets>=5.0 in c:\users\sugye\anaconda3\lib\site-packages (from nbconvert>=5->dataframe_image) (5.7.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sugye\anaconda3\lib\site-packages (from pandas>=0.24->dataframe_image) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\sugye\anaconda3\lib\site-packages (from pandas>=0.24->dataframe_image) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\sugye\anaconda3\lib\site-packages (from pandas>=0.24->dataframe_image) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\sugye\anaconda3\lib\site-packages (from pandas>=0.24->dataframe_image) (1.24.3)
Requirement already satisfied: attrs>=17.3.0 in c:\users\sugye\anaconda3\lib\site-packages (from aiohttp->dataframe_image) (22.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in c:\users\sugye\anaconda3\lib\site-packages (from aiohttp->dataframe_image) (2.0.4)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\sugye\anaconda3\lib\site-packages (from aiohttp->dataframe_image) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\sugye\anaconda3\lib\site-packages (from aiohttp->dataframe_image) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\sugye\anaconda3\lib\site-packages (from aiohttp->dataframe_image) (1.8.1)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\sugye\anaconda3\lib\site-packages (from aiohttp->dataframe_image) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\sugye\anaconda3\lib\site-packages (from aiohttp->dataframe_image) (1.2.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\sugye\anaconda3\lib\site-packages (from beautifulsoup4->dataframe_image) (2.4)
Collecting websocket-client<2.0.0,>=1.0.0 (from html2image->dataframe_image)
  Obtaining dependency information for websocket-client<2.0.0,>=1.0.0 from https://files.pythonhosted.org/packages/5a/84/44687a29792a70e111c5c477230a72c4b957d88d16141199bf9acb7537a3/websocket_client-1.8.0-py3-none-any.whl.metadata
  Downloading websocket_client-1.8.0-py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sugye\anaconda3\lib\site-packages (from requests->dataframe_image) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sugye\anaconda3\lib\site-packages (from requests->dataframe_image) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sugye\anaconda3\lib\site-packages (from requests->dataframe_image) (2023.7.22)
Requirement already satisfied: platformdirs>=2.5 in c:\users\sugye\anaconda3\lib\site-packages (from jupyter-core>=4.7->nbconvert>=5->dataframe_image) (3.10.0)
Requirement already satisfied: pywin32>=300 in c:\users\sugye\anaconda3\lib\site-packages (from jupyter-core>=4.7->nbconvert>=5->dataframe_image) (305.1)
Requirement already satisfied: jupyter-client>=6.1.5 in c:\users\sugye\anaconda3\lib\site-packages (from nbclient>=0.5.0->nbconvert>=5->dataframe_image) (7.4.9)
Requirement already satisfied: nest-asyncio in c:\users\sugye\anaconda3\lib\site-packages (from nbclient>=0.5.0->nbconvert>=5->dataframe_image) (1.5.6)
Requirement already satisfied: fastjsonschema in c:\users\sugye\anaconda3\lib\site-packages (from nbformat>=5.1->nbconvert>=5->dataframe_image) (2.16.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\sugye\anaconda3\lib\site-packages (from nbformat>=5.1->nbconvert>=5->dataframe_image) (4.17.3)
Requirement already satisfied: six>=1.5 in c:\users\sugye\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.24->dataframe_image) (1.16.0)
Requirement already satisfied: webencodings in c:\users\sugye\anaconda3\lib\site-packages (from bleach->nbconvert>=5->dataframe_image) (0.5.1)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\sugye\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=5.1->nbconvert>=5->dataframe_image) (0.18.0)
Requirement already satisfied: pyzmq>=23.0 in c:\users\sugye\anaconda3\lib\site-packages (from jupyter-client>=6.1.5->nbclient>=0.5.0->nbconvert>=5->dataframe_image) (23.2.0)
Requirement already satisfied: tornado>=6.2 in c:\users\sugye\anaconda3\lib\site-packages (from jupyter-client>=6.1.5->nbclient>=0.5.0->nbconvert>=5->dataframe_image) (6.3.2)
Downloading dataframe_image-0.2.3-py3-none-any.whl (6.7 MB)
   ---------------------------------------- 0.0/6.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/6.7 MB 660.6 kB/s eta 0:00:11
   ---------------------------------------- 0.0/6.7 MB 660.6 kB/s eta 0:00:11
    --------------------------------------- 0.1/6.7 MB 655.4 kB/s eta 0:00:11
    --------------------------------------- 0.1/6.7 MB 654.9 kB/s eta 0:00:10
   - -------------------------------------- 0.2/6.7 MB 981.9 kB/s eta 0:00:07
   - -------------------------------------- 0.3/6.7 MB 1.0 MB/s eta 0:00:07
   --- ------------------------------------ 0.5/6.7 MB 1.6 MB/s eta 0:00:04
   --- ------------------------------------ 0.6/6.7 MB 1.5 MB/s eta 0:00:05
   ----- ---------------------------------- 1.0/6.7 MB 2.4 MB/s eta 0:00:03
   ------ --------------------------------- 1.0/6.7 MB 2.4 MB/s eta 0:00:03
   ------ --------------------------------- 1.0/6.7 MB 2.4 MB/s eta 0:00:03
   ------ --------------------------------- 1.0/6.7 MB 2.4 MB/s eta 0:00:03
   -------- ------------------------------- 1.4/6.7 MB 2.3 MB/s eta 0:00:03
   -------- ------------------------------- 1.4/6.7 MB 2.3 MB/s eta 0:00:03
   -------- ------------------------------- 1.4/6.7 MB 2.3 MB/s eta 0:00:03
   ------------ --------------------------- 2.1/6.7 MB 3.0 MB/s eta 0:00:02
   ------------ --------------------------- 2.1/6.7 MB 3.0 MB/s eta 0:00:02
   ------------ --------------------------- 2.1/6.7 MB 3.0 MB/s eta 0:00:02
   ------------ --------------------------- 2.1/6.7 MB 3.0 MB/s eta 0:00:02
   -------------- ------------------------- 2.5/6.7 MB 2.7 MB/s eta 0:00:02
   ----------------- ---------------------- 2.9/6.7 MB 3.0 MB/s eta 0:00:02
   ------------------- -------------------- 3.2/6.7 MB 3.2 MB/s eta 0:00:02
   --------------------- ------------------ 3.7/6.7 MB 3.4 MB/s eta 0:00:01
   ------------------------ --------------- 4.0/6.7 MB 3.6 MB/s eta 0:00:01
   -------------------------- ------------- 4.5/6.7 MB 3.9 MB/s eta 0:00:01
   ---------------------------- ----------- 4.8/6.7 MB 4.0 MB/s eta 0:00:01
   ------------------------------ --------- 5.1/6.7 MB 4.1 MB/s eta 0:00:01
   --------------------------------- ------ 5.5/6.7 MB 4.3 MB/s eta 0:00:01
   ----------------------------------- ---- 5.9/6.7 MB 4.4 MB/s eta 0:00:01
   -------------------------------------- - 6.4/6.7 MB 4.6 MB/s eta 0:00:01
   ---------------------------------------  6.7/6.7 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------- 6.7/6.7 MB 4.6 MB/s eta 0:00:00
Downloading cssutils-2.11.0-py3-none-any.whl (398 kB)
   ---------------------------------------- 0.0/398.2 kB ? eta -:--:--
   --------------------------------------- 398.2/398.2 kB 12.5 MB/s eta 0:00:00
Downloading html2image-2.0.4.3-py3-none-any.whl (27 kB)
Downloading websocket_client-1.8.0-py3-none-any.whl (58 kB)
   ---------------------------------------- 0.0/58.8 kB ? eta -:--:--
   ---------------------------------------- 58.8/58.8 kB ? eta 0:00:00
Installing collected packages: websocket-client, cssutils, html2image, dataframe_image
  Attempting uninstall: websocket-client
    Found existing installation: websocket-client 0.58.0
    Uninstalling websocket-client-0.58.0:
      Successfully uninstalled websocket-client-0.58.0
Successfully installed cssutils-2.11.0 dataframe_image-0.2.3 html2image-2.0.4.3 websocket-client-1.8.0
Note: you may need to restart the kernel to use updated packages.

In [14]:
import dataframe_image as dfi
dfi.export(crime_rate, 'crime_rate.png')

In [15]:
pop = pd.read_csv('자치구별 주민등록인구.csv', encoding='cp949', index_col=0)
pop = pop.rename(columns=lambda x: x.replace('힌국인', '한국인'))
pop.head()

,2020_세대수,2020_한국인,2020_등록외국인,2020_고령자,2021_세대수,2021_한국인,2021_등록외국인,2021_고령자,2022_세대수,2022_한국인,2022_등록외국인,2022_고령자
자치구,,,,,,,,,,,,
강남구,234872,539231,4824,75096,234233,533042,4758,78226,232777,529102,5001,81715
강동구,196499,459970,4028,70019,201613,462664,3808,74070,202169,460067,3970,78340
강북구,145896,308055,3514,63422,144536,299182,3381,64333,144313,293660,4042,66307
강서구,266982,580185,5716,88984,271175,574315,5453,92558,273697,569166,5472,97128
관악구,274811,495060,14743,78875,276597,485699,13750,79871,283623,486752,14474,82447

In [16]:
df = pd.concat([pop_male, pop_female, crime, crime_rate, pop], axis=1)
df.head()

,2020_20대_남자,2020_30대_남자,2020_40대_남자,2020_50대_남자,2021_20대_남자,2021_30대_남자,2021_40대_남자,2021_50대_남자,2022_20대_남자,2022_30대_남자,...,2020_등록외국인,2020_고령자,2021_세대수,2021_한국인,2021_등록외국인,2021_고령자,2022_세대수,2022_한국인,2022_등록외국인,2022_고령자
강남구,5736,10181,5750,3512,5733,10501,6018,4008,5765,10686,...,4824,75096,234233,533042,4758,78226,232777,529102,5001,81715
강동구,3599,6026,4357,4360,4321,6713,4572,4672,4389,6974,...,4028,70019,201613,462664,3808,74070,202169,460067,3970,78340
강북구,3119,3973,3644,4240,3387,4239,3642,4447,3639,4485,...,3514,63422,144536,299182,3381,64333,144313,293660,4042,66307
강서구,7431,12363,6444,5323,8264,13593,6877,5584,8684,14599,...,5716,88984,271175,574315,5453,92558,273697,569166,5472,97128
관악구,24849,20454,8698,6451,25945,21558,9189,6902,27855,23214,...,14743,78875,276597,485699,13750,79871,283623,486752,14474,82447

In [17]:
df.to_csv('concatdata_withoput_weather.csv', encoding='cp949')

In [18]:
df.columns

Index(['2020_20대_남자', '2020_30대_남자', '2020_40대_남자', '2020_50대_남자',
       '2021_20대_남자', '2021_30대_남자', '2021_40대_남자', '2021_50대_남자',
       '2022_20대_남자', '2022_30대_남자', '2022_40대_남자', '2022_50대_남자',
       '2020_20대_여자', '2020_30대_여자', '2020_40대_여자', '2020_50대_여자',
       '2021_20대_여자', '2021_30대_여자', '2021_40대_여자', '2021_50대_여자',
       '2022_20대_여자', '2022_30대_여자', '2022_40대_여자', '2022_50대_여자',
       '20년1월_범죄건수', '21년1월_범죄건수', '22년1월_범죄건수', '20년2월_범죄건수', '21년2월_범죄건수',
       '22년2월_범죄건수', '20년3월_범죄건수', '21년3월_범죄건수', '22년3월_범죄건수', '20년4월_범죄건수',
       '21년4월_범죄건수', '22년4월_범죄건수', '20년5월_범죄건수', '21년5월_범죄건수', '22년5월_범죄건수',
       '20년6월_범죄건수', '21년6월_범죄건수', '22년6월_범죄건수', '20년7월_범죄건수', '21년7월_범죄건수',
       '22년7월_범죄건수', '20년8월_범죄건수', '21년8월_범죄건수', '22년8월_범죄건수', '20년9월_범죄건수',
       '21년9월_범죄건수', '22년9월_범죄건수', '20년10월_범죄건수', '21년10월_범죄건수', '22년10월_범죄건수',
       '20년11월_범죄건수', '21년11월_범죄건수', '22년11월_범죄건수', '20년12월_범죄건수',
       '21년12월_범죄건수', '22년12월_범죄건수', '20년_범죄율', '21년_범죄율', '22년_범죄율', '총범죄건수',
       '2020_세대수', '2020_한국인', '2020_등록외국인', '2020_고령자', '2021_세대수',
       '2021_한국인', '2021_등록외국인', '2021_고령자', '2022_세대수', '2022_한국인',
       '2022_등록외국인', '2022_고령자'],
      dtype='object')

## StandardScaler and MinMaxScaler

In [19]:
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import MinMaxScaler
# from sklearn.preprocessing import StandardScaler

In [20]:
print('feature mean')
print(df.mean())
print('feature var')
print(df.var())

feature mean
2020_20대_남자      6276.80
2020_30대_남자      6911.48
2020_40대_남자      4138.96
2020_50대_남자      3805.80
2021_20대_남자      6721.16
                 ...
2021_고령자        64216.64
2022_세대수       177851.84
2022_한국인       377134.88
2022_등록외국인       9571.88
2022_고령자        66696.44
Length: 76, dtype: float64
feature var
2020_20대_남자    2.121590e+07
2020_30대_남자    1.443382e+07
2020_40대_남자    2.231229e+06
2020_50대_남자    1.343251e+06
2021_20대_남자    2.319006e+07
                   ...
2021_고령자       3.584072e+08
2022_세대수       3.217197e+09
2022_한국인       1.614719e+10
2022_등록외국인     3.467302e+07
2022_고령자       4.045865e+08
Length: 76, dtype: float64

In [21]:
mm_scaler = MinMaxScaler()

In [22]:
mm_scaler.fit(df)
df_normalized = pd.DataFrame(mm_scaler.fit_transform(df), columns=df.columns)

In [23]:
df_normalized

,2020_20대_남자,2020_30대_남자,2020_40대_남자,2020_50대_남자,2021_20대_남자,2021_30대_남자,2021_40대_남자,2021_50대_남자,2022_20대_남자,2022_30대_남자,...,2020_등록외국인,2020_고령자,2021_세대수,2021_한국인,2021_등록외국인,2021_고령자,2022_세대수,2022_한국인,2022_등록외국인,2022_고령자
0,0.172884,0.426762,0.577953,0.364266,0.158815,0.410356,0.573790,0.4212,0.147335,0.383039,...,0.104712,0.733475,0.779879,0.766169,0.122802,0.734444,0.765121,0.759087,0.130046,0.721618
1,0.080405,0.194911,0.378525,0.547696,0.100050,0.208351,0.379435,0.5540,0.094222,0.200236,...,0.074068,0.659883,0.630860,0.634827,0.080395,0.677745,0.627069,0.630856,0.080498,0.678634
2,0.059633,0.080353,0.276450,0.521739,0.061179,0.076419,0.254435,0.5090,0.065272,0.077662,...,0.054281,0.564258,0.370113,0.329732,0.061334,0.544905,0.366120,0.321758,0.083958,0.525383
3,0.246235,0.548518,0.677309,0.756003,0.264150,0.575245,0.689247,0.7364,0.260007,0.575741,...,0.139051,0.934786,0.948643,0.843194,0.153826,0.929972,0.949683,0.833505,0.152682,0.917917
4,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0000,1.000000,1.000000,...,0.486565,0.788253,0.973412,0.677816,0.524194,0.756886,0.994452,0.680423,0.585304,0.730941
5,0.311451,0.292729,0.371797,0.491456,0.313634,0.298048,0.361425,0.4836,0.304281,0.306215,...,0.435902,0.377819,0.477072,0.405900,0.474243,0.372870,0.478779,0.403034,0.554642,0.369546
6,0.118357,0.229451,0.397566,0.541207,0.125312,0.239868,0.379839,0.5296,0.128961,0.250714,...,1.000000,0.662478,0.536369,0.511824,1.000000,0.657840,0.543565,0.510580,1.000000,0.647431
7,0.124805,0.199487,0.264567,0.514168,0.139004,0.218003,0.263844,0.4886,0.144980,0.230178,...,0.538882,0.222459,0.247037,0.202135,0.538925,0.227138,0.254580,0.202846,0.522924,0.227629
8,0.148001,0.098153,0.284324,0.431971,0.151864,0.112255,0.272177,0.4346,0.140387,0.106323,...,0.072798,0.884125,0.702880,0.724951,0.088519,0.872495,0.696397,0.711966,0.095396,0.853116
9,0.000000,0.019251,0.153185,0.294830,0.000000,0.023997,0.155645,0.2782,0.000000,0.026199,...,0.000000,0.544500,0.343251,0.363667,0.000000,0.542545,0.339252,0.355256,0.000000,0.534183
10,0.364679,0.188885,0.327416,0.486697,0.378267,0.193313,0.315591,0.4762,0.359941,0.194819,...,0.464775,0.540688,0.478305,0.401055,0.562405,0.515955,0.481404,0.401600,0.704633,0.501961
11,0.376623,0.319904,0.331854,0.269738,0.382887,0.328605,0.338710,0.2740,0.380361,0.325569,...,0.317524,0.589885,0.554107,0.490789,0.306848,0.576011,0.553118,0.483240,0.362409,0.549887
12,0.284057,0.327270,0.369077,0.221285,0.290411,0.335591,0.357392,0.2294,0.267418,0.329853,...,0.302741,0.432481,0.531490,0.459851,0.347023,0.411875,0.527459,0.453598,0.415802,0.393018
13,0.238532,0.129736,0.162777,0.182998,0.245963,0.129160,0.169220,0.1872,0.227776,0.126711,...,0.333962,0.430640,0.366052,0.340251,0.394295,0.407591,0.372814,0.345305,0.524894,0.394063
14,0.087848,0.215278,0.266142,0.143413,0.081655,0.211071,0.271102,0.1582,0.070714,0.195656,...,0.069102,0.517104,0.487556,0.540797,0.083966,0.495041,0.471824,0.527316,0.087995,0.474948
15,0.175177,0.130573,0.212312,0.298075,0.175712,0.132892,0.200000,0.2818,0.171305,0.122427,...,0.186518,0.305966,0.323045,0.305112,0.208687,0.299977,0.316471,0.298242,0.237361,0.288660
16,0.310715,0.163942,0.282319,0.420074,0.317505,0.173475,0.279973,0.3806,0.297371,0.167290,...,0.300239,0.714255,0.600727,0.574854,0.339568,0.686462,0.604125,0.575744,0.446559,0.667618
17,0.180673,0.454327,0.630064,0.608912,0.183161,0.450725,0.634409,0.6126,0.170533,0.440362,...,0.148676,1.000000,1.000000,1.000000,0.161593,1.000000,1.000000,1.000000,0.164264,1.000000
18,0.025619,0.096758,0.212885,0.351071,0.027634,0.104576,0.210887,0.3312,0.027676,0.107407,...,0.054897,0.596843,0.538538,0.606158,0.052585,0.603487,0.532434,0.595218,0.040081,0.602894
19,0.238835,0.428324,0.463422,0.592256,0.248127,0.451259,0.454704,0.5762,0.240051,0.450704,...,0.992570,0.539123,0.564194,0.474654,0.984912,0.520116,0.566915,0.474099,0.966696,0.506317
20,0.061667,0.153674,0.185970,0.145576,0.062635,0.159983,0.182258,0.1436,0.059328,0.162464,...,0.481252,0.228330,0.217074,0.187470,0.550174,0.200248,0.210478,0.182429,0.592993,0.178074
21,0.108058,0.209308,0.402577,0.506165,0.111204,0.209951,0.379301,0.5072,0.102984,0.203979,...,0.080998,0.879747,0.690696,0.654689,0.082984,0.857433,0.679871,0.643262,0.075019,0.822678
22,0.073438,0.009709,0.006299,0.039585,0.065382,0.004053,0.002554,0.0386,0.065928,0.000000,...,0.289036,0.058155,0.045569,0.041400,0.316891,0.046740,0.042329,0.038899,0.410275,0.036972
23,0.027956,0.000000,0.000000,0.000000,0.022432,0.000000,0.000000,0.0000,0.013317,0.007682,...,0.280682,0.000000,0.000000,0.000000,0.325016,0.000000,0.000000,0.000000,0.387015,0.000000
24,0.091527,0.190726,0.447960,0.966256,0.091518,0.190593,0.413844,0.9110,0.093643,0.192751,...,0.106098,0.651592,0.558219,0.494273,0.112847,0.645166,0.560515,0.492011,0.121444,0.635077

In [24]:
df_normalized[4:5]

,2020_20대_남자,2020_30대_남자,2020_40대_남자,2020_50대_남자,2021_20대_남자,2021_30대_남자,2021_40대_남자,2021_50대_남자,2022_20대_남자,2022_30대_남자,...,2020_등록외국인,2020_고령자,2021_세대수,2021_한국인,2021_등록외국인,2021_고령자,2022_세대수,2022_한국인,2022_등록외국인,2022_고령자
4,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.486565,0.788253,0.973412,0.677816,0.524194,0.756886,0.994452,0.680423,0.585304,0.730941

In [25]:
feature_df_scaled = pd.DataFrame(data=df_normalized, columns=df.columns)

print('feature mean') 
print(feature_df_scaled.mean()) 

print('feature var') 
print(feature_df_scaled.var())

feature mean
2020_20대_남자    0.196287
2020_30대_남자    0.244321
2020_40대_남자    0.347310
2020_50대_남자    0.427817
2021_20대_남자    0.199940
                 ...
2021_고령자       0.543318
2022_세대수       0.517391
2022_한국인       0.476811
2022_등록외국인     0.349715
2022_고령자       0.530343
Length: 76, dtype: float64
feature var
2020_20대_남자    0.039732
2020_30대_남자    0.044942
2020_40대_남자    0.045731
2020_50대_남자    0.062851
2021_20대_남자    0.040167
                 ...
2021_고령자       0.066708
2022_세대수       0.065447
2022_한국인       0.055712
2022_등록외국인     0.080081
2022_고령자       0.065626
Length: 76, dtype: float64